language: java

cache:
  directories:
  - $HOME/.m2

services:
  - docker

before_install:
  - docker pull postgres
  - docker run --name nb-server -e POSTGRES_PASSWORD=nb_root -e POSTGRES_USER=nb_root -e POSTGRES_DB=nb_server -p 2222:5432 --restart=always -d postgres
  - docker ps -a

install:
  - mvn clean test -Dspring.datasource.url=jdbc:postgresql://127.0.0.1:2222/nb_server